name: Build-ImmortalWrt

on:
  # schedule: [ cron: 0 2 */7 * * ]
  # watch:
  #   types: started
  workflow_dispatch:
    inputs:
      branch:
        description: '选择ImmortalWrt仓库分支：'
        default: 'openwrt-23.05'
        required: true
        type: choice
        options: [openwrt-21.02, openwrt-23.05, master, openwrt-18.06-k5.4, openwrt-18.06]

      target:
        description: '选择要编译的机型：'
        default: 'x86_64'
        required: true
        type: choice
        options: [x86_64, r1-plus-lts, newifi-d2, asus_rt-n16, phicomm_k2p, armvirt-64-default, r4s, r2s, r2c]

      ip:
        description: '设置web登录IP：'
        default: '192.168.2.1'
        required: false

      partsize:
        description: '设置rootfs大小：'
        default: '800'
        required: false

      free_disk:
        description: '整理空间'
        type: choice
        default: 'false'
        options: [losetup, free-disk-space, plus, no]
        required: false

env:
  REPO_FLODER: openwrt
  UPLOAD_RELEASE: true
  UPLOAD_BIN_DIR: true
  UPLOAD_PACKAGES: true
  UPLOAD_SYSUPGRADE: true

jobs:
  immo-openwrt:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id
    name: immortalwrt-${{ github.event.inputs.branch }}-${{ github.event.inputs.target }}

    permissions:
      contents: write

    env:
      IP: ${{ github.event.inputs.ip }}
      PARTSIZE: ${{ github.event.inputs.partsize }}
      REPO_BRANCH: ${{ github.event.inputs.branch }}
      FREE_DISK: ${{ github.event.inputs.free_disk }}
      TARGET_DEVICE: ${{ github.event.inputs.target }}

    steps:
    - name: 系统信息
      run: |
        echo "警告⚠"
        echo "分配的服务器性能有限，若选择的插件过多，务必注意CPU性能！"
        echo -e "已知CPU型号(降序): 7763，8370C，8272CL，8171M，E5-2673\n"
        echo "==========================CPU信息=========================="
        echo "CPU物理数量: $(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
        echo "CPU线程数量: $(nproc)"
        echo -e "CPU型号信息:$(cat /proc/cpuinfo | grep -m1 name | awk -F: '{print $2}')\n"
        echo "==========================内存信息=========================="
        echo "已安装内存详细信息:"
        echo -e "$(sudo lshw -short -C memory | grep GiB)\n"
        echo "==========================硬盘信息=========================="
        echo "硬盘数量: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT
        Emoji=("🎉" "🤞" "✨" "🎁" "🎈" "🎄" "🎨" "💋" "🍓" "🍕" "🍉" "💐" "🌴" "🚀" "🗽" "⛅" "🌈" "🔥" "⛄" "🐶" "🏅" "🦄" "🐤")
        RANDOM=$$$(date +%s); rand=$[$RANDOM % ${#Emoji[@]}]
        echo "EMOJI=${Emoji[$rand]}" >>$GITHUB_ENV

    - name: jlumbroso 整理空间
      if: env.FREE_DISK == 'free-disk-space' || env.FREE_DISK == 'plus'
      uses: jlumbroso/free-disk-space@main
      with:
        dotnet: true
        android: true
        haskell: true
        tool-cache: true
        swap-storage: true
        large-packages: true

    - name: losetup 整理空间
      if: env.FREE_DISK == 'losetup' || env.FREE_DISK == 'plus'
      run: |
        [ -f /mnt/swapfile ] && sudo swapoff -a && sudo rm -f /mnt/swapfile
        MNT_SIZE=$((($(df --block-size=1024 --output=avail /mnt | tail -1) - 1024*1024*1) * 1024))
        sudo fallocate -l $MNT_SIZE /mnt/mnt.img
        MNT_NAME=$(sudo losetup -Pf --show /mnt/mnt.img)
        sudo pvcreate -f $MNT_NAME
        ROOT_SIZE=$((($(df --block-size=1024 --output=avail / | tail -1) - 1024*1024*4) * 1024))
        sudo fallocate -l $ROOT_SIZE /root.img
        ROOT_NAME=$(sudo losetup -Pf --show /root.img)
        sudo pvcreate -f $ROOT_NAME
        sudo vgcreate actions $MNT_NAME $ROOT_NAME
        sudo lvcreate -n disk -l 100%FREE actions
        LV_NAME=$(sudo lvscan | awk -F "'" '{print $2}')
        sudo mkfs.btrfs -L combinedisk $LV_NAME
        sudo mount -o compress=zstd $LV_NAME $GITHUB_WORKSPACE
        sudo chown -R runner:runner $GITHUB_WORKSPACE && df -hT

    - name: Checkout
      uses: actions/checkout@v4.2.0

    - name: 安装编译依赖
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        (docker rmi $(docker images -q)
        sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android $AGENT_TOOLSDIRECTORY
        sudo -E apt-get -y update
        sudo -E apt-get -y install clang rename $(curl -fsSL is.gd/depends_ubuntu_2204)
        sudo -E systemctl daemon-reload
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get -y clean) &
        sudo -E timedatectl set-timezone "Asia/Shanghai"

    - name: 部署
      run: bash immortalwrt_openwrt.sh

    - name: Cache Toolchain
      if: env.CACHE_ACTIONS == 'true'
      uses: HiGarfield/cachewrtbuild@main
      with:
        ccache: true
        clean: ${{ env.CLEAN }}
        mixkey: ${{ env.CACHE_NAME }}
        prefix: ${{ GITHUB.WORKSPACE }}/${{ env.REPO_FLODER }}

    - name: Compile Toolchain
      id: tools
      if: env.CACHE_ACTIONS == 'true' && !cancelled()
      run: |
        cd $REPO_FLODER
        make -j$(nproc) toolchain/compile || make -j1 V=s toolchain/compile
        bash immortalwrt_openwrt.sh

    - name: 上传 Cache 到 Release
      if: steps.tools.conclusion == 'success' || env.OUTPUT_RELEASE == 'true' && !cancelled()
      uses: softprops/action-gh-release@v2.0.8
      with:
        files: output/*
        token: ${{ secrets.GITHUB_TOKEN }}
        body: immortalwrt-Cache
        tag_name: immortalwrt-Cache
        name: ${{ env.EMOJI }} immortalwrt-Cache ${{ env.EMOJI }}

    - name: 下载软件包
      run: |
        cd $REPO_FLODER
        #make package/download -j$(nproc)
        n=0; while true; do make package/download -j && break || (n=$((n+1)); [ $n -eq 3 ] && break); done
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: 固件编译
      id: compile
      timeout-minutes: 1440
      run: cd $REPO_FLODER && make -j$(nproc) || make -j1 V=s

    - name: 上传 Bin 到 Artifact
      if: steps.organize.conclusion == 'success' && env.UPLOAD_BIN_DIR == 'true' && !cancelled()
      uses: actions/upload-artifact@v4.4.0
      with:
        path: ${{ env.REPO_FLODER }}/bin
        name: OpenWrt-${{ env.TARGET_DEVICE }}-bin

    - name: 筛选固件
      id: organize
      if: steps.compile.conclusion == 'success' && !cancelled()
      run: |
        df -hT
        cd $REPO_FLODER
        echo "======================="
        du -h --max-depth=1 ./bin
        du -h --max-depth=1 ./build_dir
        du -h --max-depth=1 ./staging_dir
        du -h --max-depth=1 ./ --exclude=bin --exclude=build_dir --exclude=staging_dir --exclude=bin
        ls bin/targets/*/*/
        sf=${CACHE_NAME%%-*}-${REPO_BRANCH#*-}-$(TZ=UTC-8 date +%m-%d)
        ARCH=$(awk -F '"' '/ARCH_PACKAGES/{print $2}' .config)
        [[ $FIRMWARE_TYPE ]] && cp -v $(find bin/targets/ -type f -name "*${FIRMWARE_TYPE}*") ../firmware && echo "upload_firmware=true" >>$GITHUB_ENV || true
        tar -zcPf ../firmware/$sf-$ARCH-packages.tar.gz bin/packages/ && echo "upload_packages=true" >>$GITHUB_ENV || true
        cd ../firmware && md5sum * >$sf-$TARGET_DEVICE-md5-config.txt || true
        sed '/^$/d' ../$REPO_FLODER/.config >>$sf-$TARGET_DEVICE-md5-config.txt || true
        echo "FIRMWARE=$PWD" >>$GITHUB_ENV
        echo "STRDATE=$(TZ=UTC-8 date +%Y-%m-%d)" >>$GITHUB_ENV

    - name: 上传 Packages 到 Artifact
      if: env.upload_packages == 'true' && env.UPLOAD_PACKAGES == 'true' && !cancelled()
      uses: actions/upload-artifact@v4.4.0
      with:
        path: firmware/*packages.tar.gz
        name: OpenWrt-${{ env.TARGET_DEVICE }}-package

    - name: 上传 Firmware 到 Artifact
      if: env.upload_firmware == 'true' && env.UPLOAD_SYSUPGRADE == 'true' && !cancelled()
      uses: actions/upload-artifact@v4.4.0
      with:
        path: firmware/*${{ env.FIRMWARE_TYPE }}*
        name: OpenWrt-${{ env.TARGET_DEVICE }}-firmware

    - name: 上传 Firmware 到 Release
      if: env.upload_firmware == 'true' && env.UPLOAD_RELEASE == 'true' && !cancelled()
      uses: softprops/action-gh-release@v2.0.8
      with:
        files: firmware/*
        token: ${{ secrets.GITHUB_TOKEN }}
        body: immortalwrt-firmware
        tag_name: ${{ env.STRDATE }}-immortalwrt
        name: ${{ env.EMOJI }} ${{ env.STRDATE }} immortalwrt-firmware ${{ env.EMOJI }}

    - name: Delete Releases
      if: (!cancelled())
      uses: dev-drprasad/delete-older-releases@v0.3.4
      with:
        keep_latest: 15
        delete_tags: true
        delete_tag_pattern: ^.*immortalwrt$
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
